language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build
env:
  global:
  - PACKAGE=jbuilder
  matrix:
  - OCAML_VERSION=4.02 OCAML_RELEASE=3
  - OCAML_VERSION=4.03 OCAML_RELEASE=0
  - OCAML_VERSION=4.04 OCAML_RELEASE=2
  - OCAML_VERSION=4.05 OCAML_RELEASE=0+rc1
os:
  - linux
  - osx
