language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.06 OCAML_RELEASE=0 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
