language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

matrix:
  include:
  - os: linux
    env: OCAML_VERSIONS=4.02.3
    stage: Build
  - os: linux
    env: OCAML_VERSIONS=4.03.0
    stage: Build
  - os: linux
    env: OCAML_VERSIONS=4.04.2
    stage: Build
  - os: linux
    env: OCAML_VERSIONS=4.05.0
    stage: Build
  - os: linux
    env: OCAML_VERSIONS=4.06.0
    stage: Build
  - os: linux
    env: OPAM_OCAML_VERSION=4.05.0
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: osx
    env: OCAML_VERSIONS="4.02.3 4.03.0 4.04.2"
    stage: macOS
  - os: osx
    env: OCAML_VERSIONS="4.05.0 4.06.0" OPAM_OCAML_VERSION=4.05.0
    stage: macOS
