language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

# Please keep the list in sync with the minimal version of OCaml in
# dune-project, dune.opam.template and bootstrap.ml

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.09 OCAML_RELEASE=0 WITH_OPAM=1 OPAM_RESET=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
